from maintenance import calculate_weekly_maintenance


WINDOW_WIDTH = 1500
WINDOW_HEIGHT = 1000

TOP_BAR_HEIGHT = 50
BOTTOM_BAR_HEIGHT = 50
PLAY_AREA_TOP = TOP_BAR_HEIGHT
PLAY_AREA_BOTTOM = WINDOW_HEIGHT - BOTTOM_BAR_HEIGHT
PLAY_AREA_WIDTH = WINDOW_WIDTH
PLAY_AREA_HEIGHT = PLAY_AREA_BOTTOM - PLAY_AREA_TOP

TILE_SIZE = 20
# A világ mérete független az ablak és a viewport aktuális méretétől.
WORLD_WIDTH_TILES = 100
WORLD_HEIGHT_TILES = 80

# A régi nevek kompatibilitási aliasok; mindenhol ugyanazt a központi
# világméretet jelentik.
GRID_COLS = WORLD_WIDTH_TILES
GRID_ROWS = WORLD_HEIGHT_TILES
FIELD_SIZE = 4

GRASS = 0
ROAD = 1
FIELD = 2
BUILDING = 3

TOOL_INSPECT = 0
TOOL_ROAD = 1
TOOL_BULLDOZER = 2
TOOL_BUILD = 3
TOOL_PLANT = 4
TOOL_HARVEST = 5
TOOL_ANIMAL_HUSBANDRY = 6
TOOL_FERTILIZE = 7
TOOL_WATERING = 8
TOOL_ORCHARD = 9

# Gazdasági alapértékek
STARTING_MONEY = 10000.00
ROAD_BUILD_COST = 20.00
FARMHOUSE_BUILD_COST = 1000.00
FARMHOUSE_LEVEL_2_UPGRADE_PRICE = 5000.00
FARMHOUSE_LEVEL_2_MAINTENANCE_BASE = 5000.00
FARMHOUSE_LEVEL_3_UPGRADE_PRICE = 15000.00
FARMHOUSE_LEVEL_3_MAINTENANCE_BASE = 15000.00
WAREHOUSE_BUILD_COST = 500.00
MARKET_BUILD_COST = 500.00
GARAGE_BUILD_COST = 500.00
ANIMAL_PEN_BUILD_COST = 400.00
POND_BUILD_COST = 500.00
ORCHARD_BUILD_COST = 200.00
PROCESSING_PLANT_BUILD_COST = 3000.00
TRACTOR_PURCHASE_PRICE = 500.00
COMBINE_PURCHASE_PRICE = 500.00
FRUIT_HARVESTER_PURCHASE_PRICE = 500.00
WATER_TANK_PURCHASE_PRICE = 300.00
TRAILER_PURCHASE_PRICE = 300.00
AUTO_PURCHASE_DELIVERY_COST_PER_UNIT = 3.00

# Régi külső hivatkozások kompatibilitási értékei; mind ugyanabból a
# központi, vételár-alapú szabályból származnak.
ROAD_WEEKLY_COST = calculate_weekly_maintenance(ROAD_BUILD_COST)
FARMHOUSE_WEEKLY_COST = calculate_weekly_maintenance(FARMHOUSE_BUILD_COST)
WAREHOUSE_WEEKLY_COST = calculate_weekly_maintenance(WAREHOUSE_BUILD_COST)
MARKET_WEEKLY_COST = calculate_weekly_maintenance(MARKET_BUILD_COST)
GARAGE_WEEKLY_COST = calculate_weekly_maintenance(GARAGE_BUILD_COST)
ANIMAL_PEN_WEEKLY_COST = calculate_weekly_maintenance(ANIMAL_PEN_BUILD_COST)
POND_WEEKLY_COST = calculate_weekly_maintenance(POND_BUILD_COST)
ORCHARD_WEEKLY_COST = calculate_weekly_maintenance(ORCHARD_BUILD_COST)
PROCESSING_PLANT_WEEKLY_COST = calculate_weekly_maintenance(
    PROCESSING_PLANT_BUILD_COST,
)
TRACTOR_WEEKLY_COST = calculate_weekly_maintenance(TRACTOR_PURCHASE_PRICE)
COMBINE_WEEKLY_COST = calculate_weekly_maintenance(COMBINE_PURCHASE_PRICE)
FRUIT_HARVESTER_WEEKLY_COST = calculate_weekly_maintenance(
    FRUIT_HARVESTER_PURCHASE_PRICE,
)
WATER_TANK_WEEKLY_COST = calculate_weekly_maintenance(WATER_TANK_PURCHASE_PRICE)
TRAILER_WEEKLY_COST = calculate_weekly_maintenance(TRAILER_PURCHASE_PRICE)

# Külső kiegészítések visszafelé kompatibilis nevei; az új kód nem használja.
ROAD_DAILY_COST = ROAD_WEEKLY_COST
FARMHOUSE_DAILY_COST = FARMHOUSE_WEEKLY_COST
WAREHOUSE_DAILY_COST = WAREHOUSE_WEEKLY_COST
MARKET_DAILY_COST = MARKET_WEEKLY_COST
GARAGE_DAILY_COST = GARAGE_WEEKLY_COST
ANIMAL_PEN_DAILY_COST = ANIMAL_PEN_WEEKLY_COST
POND_DAILY_COST = POND_WEEKLY_COST
ORCHARD_DAILY_COST = ORCHARD_WEEKLY_COST
PROCESSING_PLANT_DAILY_COST = PROCESSING_PLANT_WEEKLY_COST
TRACTOR_DAILY_COST = TRACTOR_WEEKLY_COST
COMBINE_DAILY_COST = COMBINE_WEEKLY_COST
FRUIT_HARVESTER_DAILY_COST = FRUIT_HARVESTER_WEEKLY_COST
WATER_TANK_DAILY_COST = WATER_TANK_WEEKLY_COST
TRAILER_DAILY_COST = TRAILER_WEEKLY_COST

COLOR_GRASS = (34, 139, 34)
COLOR_ROAD = (123, 105, 84)
COLOR_FIELD = (110, 70, 20)
COLOR_GRID = (50, 180, 50)
COLOR_PREVIEW_OK = (255, 255, 0)
COLOR_PREVIEW_ERROR = (255, 0, 0)
COLOR_BUTTON = (220, 220, 220)
COLOR_BUTTON_ACTIVE = (180, 220, 180)
COLOR_BUTTON_BORDER = (80, 80, 80)
COLOR_TEXT = (0, 0, 0)
COLOR_TOOLBAR = (210, 210, 210)
COLOR_TOOLBAR_LINE = (120, 120, 120)
